name: PHP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"

    - name: Deploy via SSH
      run: |
        # Ajouter la clé SSH de l'hôte à known_hosts
        ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
        # Cloner le référentiel Git sur le serveur distant
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /cabinet-xaviertermeau.com && git pull origin main || git clone https://github.com/Abdoulrachard/justice-suite.git /cabinet-xaviertermeau.com'
    
        # Installer les dépendances avec Composer
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /cabinet-xaviertermeau.com && composer install --no-dev --optimize-autoloader'
    
        
        